dist: trusty
sudo: false

language: node_js
node_js:
  - '11'

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g karma
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - karma start my.conf.js --singleRun

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/lcov.info
  - ./cc-test-reporter sum-coverage coverage/codeclimate.frontend.json                  # Sum both coverage parts into coverage/codeclimate.json
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT